# List Python plugins to include here

#tests/TestLoadPlugin.py
## event 'OnPluginLoad'
## event 'OnPluginUnload'

#tests/TestImportsPlugin.py
#tests/TestExceptionTracebackPlugin.py
#tests/TestLoadAnotherFile.py
#tests/TestPlayerHurt.py
## event 'player_take_damage' #fake event from detour
## event 'player_hurt'

#tests/TestPlayerDeath.py
## event 'player_death'

#tests/TestConnections.py
## event 'player_connect'
## event 'player_connect_full'
## event 'player_disconnect'

#tests/TestPlayerSpawn.py
## event 'player_activate'
## event 'player_spawn_fake'
### Despite it's name, it's a real player_spawn event but we use a py::dict and not IGameEvent
## event 'player_spawned'

#tests/TestPlayerJump.py
# player_jump exists in gamedata but _airborn and _land dont so they are defined
# in ~/CS2Fixes/resource/adventure.res and loaded by g_gameEventManager->LoadEventsFromFile
# they are true game_events but the engine won't call them.
## event 'player_jump'
## event 'player_airborn'
## event 'player_land'

#####above tested 9/26/26
tests/TestPlayerInputs.py
# Keybinds ability1, ability2, ultimate are used to interact with python events.
# use_ability1 - Will use the template scroll with a template technique and technique modifier (does nothing but some indicating console messages)
# use_ability2 - Will list in console each trackable key in the pawn.buttonstates bitvector
# use_ultimate - Will list in console the name of and distance to each other player within range, first 400.0 using GetPlayersNearPlayerID_list; then 
#              - second 800.0 using GetPlayersNearPlayerID_dict showing their name and range, changing the return_difference argument to false will return their coordinates instead.
# 
# player_spawn - Assigns a dispatch event for the spawning player to trigger on player_death to Explode, damage not applied yet.
# player_death - Tells the event_manager to attempt to use any 'player_death' dispatches the dying player has. (see above)
# 
# *Currently there are many messages printed to the console log so with even a couple bots it will be spammy, each message can be several lines long of information.



#tests/TestPyMySQL.py
##Check for Database or Add
##Check for Table or Add
##Check for Connecting Player or Add
##Count kills for Player
##Print killcount


#Adventure/Adventure.py


###################tests/TestEffects.py
## Here we go, time to make some nifty effects
## playsound
## create sprite

##junk below is old work to pull from while making 
##better working examples above
###################SampleEvents.py
###################ManyRaces/AdventureTest.py

#tests/TestOnAllPluginsLoaded.py
##MenuSystem by Wend4r python interface to CS2Fixes.
##When a player connects UpdatePlayerItems is called by CPP which requests Python to send the players' info
##When a player opens a menu by '!menu' display that info and if stale, update it.

