# List Python plugins to include here

#tests/TestLoadPlugin.py
## event 'OnPluginLoad'
## event 'OnPluginUnload'

#tests/TestImportsPlugin.py
#tests/TestExceptionTracebackPlugin.py
#tests/TestLoadAnotherFile.py
#tests/TestPlayerHurt.py
## event 'player_take_damage' #fake event from detour
## event 'player_hurt'

#tests/TestPlayerDeath.py
## event 'player_death'

#tests/TestConnections.py
## event 'player_connect'
## event 'player_connect_full'
## event 'player_disconnect'

#####above tested 9/24/26
tests/TestPlayerSpawn.py
## event 'player_activate'
## event 'player_spawn_fake'
### Despite it's name, it's a real player_spawn event but we use a py::dict and not IGameEvent
## event 'player_spawned'

#tests/TestPlayerJump.py
## event 'OnPlayerJump'
## event 'OnPlayerLand'
## event 'OnPlayerAirborn'

#tests/TestPlayerInputs.py
## buttons'n'bindings and stuff in here, lets see.
## Check and report button states on player_jump and the following python captures
## python capture 'OnClientCommand' but not as game event
## python capture 'OnClientAbility1' but not as game event
## python capture 'OnClientAbility2' but not as game event
## python capture 'OnClientUltimate' but not as game event

#tests/TestOnAllPluginsLoaded.py
##MenuSystem by Wend4r python interface to CS2Fixes.
##When a player connects UpdatePlayerItems is called by CPP which requests Python to send the players' info
##When a player opens a menu by '!menu' display that info and if stale, update it.

#tests/TestPyMySQL.py
##Check for Database or Add
##Check for Table or Add
##Check for Connecting Player or Add
##Count kills for Player
##Print killcount


#Adventure/Adventure.py


###################tests/TestEffects.py
## Here we go, time to make some nifty effects
## playsound
## create sprite

##junk below is old work to pull from while making 
##better working examples above
###################SampleEvents.py
###################ManyRaces/AdventureTest.py

